#prod.gocd.yaml
format_version: 1
environments:
  TestEnviroment:
    pipelines:
      - TestGdcOSS
      
pipelines:
  TestGdcOSS: # definition of yaml-example pipeline
    group: grupoTestBea
    label_template: "${COUNT}"
    locking: off
    materials:
      mygit: # this is the name of material
        # keyword git says about type of material and url at once
        git: git@gitlab.heart.cic.wh.telefonica:OSS/DDoS_1607.git
        branch: master
    
    stages: # list of stages in order
      - TestStage: # name of stage
          clean_workspace: true
          jobs:    
             defaultJob: # name of the job
               tasks: # ordered list of tasks to execute in job csharp
                - exec: # indicates type of task     
                   command: echo              
                   arguments:  
                   - "-c"
                   - "Hello, World!"

      
